services:
  cypress_test:
    image: cypress_template
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./dockerReports/:/app/cypress/results
      - ./dockerReports/:/app/mochawesome-report
    command: ["run", "cypress:run"]