services:
  cypress_template:
    image: cypress_temp
    container_name: cypress_template
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./dockerReports/:/app/cypress/results
      - ./dockerReports/:/app/mochawesome-report
      - ./dockerReports/:/app/allure-results