// ...existing code...
// ...existing code...

export class MockApiModule {}
// MCP refactor: NgModule removed. Convert to standalone providers or import in main.ts/app.config.ts
// ...existing code...
export const MockApiProviders = [
  // Add your providers here
];
